//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDeDatos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_producto()
        {
            this.tb_foto = new HashSet<tb_foto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string serial { get; set; }
        public int id_marca { get; set; }
        public int id_categoria { get; set; }
        public int id_tipoProducto { get; set; }
        public int id_espacio { get; set; }
        public int id_persona { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual tb_espacio tb_espacio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_foto> tb_foto { get; set; }
        public virtual tb_marca tb_marca { get; set; }
        public virtual tb_persona tb_persona { get; set; }
        public virtual tb_tipoProducto tb_tipoProducto { get; set; }
    }
}
